version: '3.8'

services:
  web:
    build:
      context: ./web
      target: dev
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    # command: sh -c "ls -la /app && ls -la /app/src && ls -la /app/src/app && npm install --ignore-scripts && npm run dev"
    command: sh -c "npm install --ignore-scripts && npm run dev"
    environment:
      - NODE_ENV=development

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile.dev
    volumes:
      - ./strapi:/opt/app
      - /opt/app/node_modules
    command: npm run develop
    environment:
      - NODE_ENV=development

  ai-service:
    volumes:
      - ./ai-service:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DEBUG=true

  mebbis-service:
    volumes:
      - ./mebbis-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
