FROM node:22-bullseye-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libvips-dev \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NODE_ENV=development
CMD ["npm", "run", "develop"]
